### ISSUE TITLE
Invalid work type errors

### ISSUE THREAD

**Issue by DezTheDapperImp** [mirkoconsiglio/Bitburner-scripts#1] opened 2022-03-26 13:05 UTC
When I try to run this script it gives the following error.
RUNTIME ERROR
/factions/work.js@home

Failed to resolve module specifier "/My Drive/Games/Bitburner/utils.js". Invalid relative url or base scheme isn't hierarchical.
stack:
TypeError: Failed to resolve module specifier "/My Drive/Games/Bitburner/utils.js". Invalid relative url or base scheme isn't hierarchical.

When I go into the in game script editor for work.js and make it: 

// noinspection JSUnresolvedVariable

import {getFactions} from 'utils.js';

/**

Then it removes that error, but comes up with another. 

RUNTIME ERROR
/factions/work.js@home

Invalid work type
stack:
Error: Invalid work type
at Module.main (blob:file:///e179c155-b8e6-4eec-92e3-d7c612df471d:24:13)
at executeJSScript (file:///D:/Gaming/Video%20Games/Platforms/Steam/steamapps/common/Bitburner/resources/app/main.bundle.js:19:90945)

I have tried verifying my game files, redownloading all the scripts, this has persisted through bitnodes and similar errors pop up for quite a few of the other scripts as well such as: 

automators/company.js faction.js
company/work.js
factions/work.js

And other scripts instantly kill themselves instead of doing anything:

Automators/ exp.js gym.js university.js

**Comment by mirkoconsiglio** [comment] 2022-03-26 14:45
Thanks for pointing this out. I know that '/My Drive/Games/Bitburner/utils.js' was an absolute path put in by Webstorm which is now changed to just '/utils.js'.

I am going to put out updates to the scripts using the new `ns.prompt` to add in drop-down selections and text fields for 'gym.js', 'university.js' and 'work.js' scripts.

**Comment by DezTheDapperImp** [comment] 2022-03-27 11:34
I also got an error with the stock Automator while I was at work, couldn't post it earlier as I hadn't gotten it yet on this Bitnode.

RUNTIME ERROR
/stock-market/autopilot.js@home

long.append is not a function
stack:
TypeError: long.append is not a function
at blob:file:///826d8bf1-4577-413d-8c92-c6840468a9da:480:32
at Array.forEach ()
at updateForecast (blob:file:///826d8bf1-4577-413d-8c92-c6840468a9da:479:12)
at refresh (blob:file:///826d8bf1-4577-413d-8c92-c6840468a9da:387:20)
at Module.main (blob:file:///826d8bf1-4577-413d-8c92-c6840468a9da:122:18)

**Comment by DezTheDapperImp** [comment] 2022-03-27 11:36
> Thanks for pointing this out. I know that '/My Drive/Games/Bitburner/utils.js' was an absolute path put in by Webstorm which is now changed to just '/utils.js'.
> 
> I am going to put out updates to the scripts using the new `ns.prompt` to add in drop-down selections and text fields for 'gym.js', 'university.js' and 'work.js' scripts.

Oh, and thanks for being so quick with the reply and fix! I honestly was expecting a day for a reply asking for more info lol.

**Comment by mirkoconsiglio** [comment] 2022-03-27 16:46
> I also got an error with the stock Automator while I was at work, couldn't post it earlier as I hadn't gotten it yet on this Bitnode.
> 
> RUNTIME ERROR /stock-market/autopilot.js@home
> 
> long.append is not a function stack: TypeError: long.append is not a function at blob:file:///826d8bf1-4577-413d-8c92-c6840468a9da:480:32 at Array.forEach () at updateForecast (blob:file:///826d8bf1-4577-413d-8c92-c6840468a9da:479:12) at refresh (blob:file:///826d8bf1-4577-413d-8c92-c6840468a9da:387:20) at Module.main (blob:file:///826d8bf1-4577-413d-8c92-c6840468a9da:122:18)

This should be fixed as I went into Python mode for a second and forgot that append is push in JS



> > Thanks for pointing this out. I know that '/My Drive/Games/Bitburner/utils.js' was an absolute path put in by Webstorm which is now changed to just '/utils.js'.
> > I am going to put out updates to the scripts using the new `ns.prompt` to add in drop-down selections and text fields for 'gym.js', 'university.js' and 'work.js' scripts.
> 
> Oh, and thanks for being so quick with the reply and fix! I honestly was expecting a day for a reply asking for more info lol.

No problem! So far I am using a repo as a means to track and store my script changes, so some of them might not be so intuitive to use. But I try my best to make them as general as I can at times and I rolled out some commits which should have fixed the bugs you mentioned, and also added some more quality of life stuff.

Also I suggest whenever there are new commits you rerun 

> run /build/download-bitburner-scripts.js

followed by 

> run /build/script-remover.js

so that any phased out scripts are removed and you can use the updated ones. Cheers!

**Comment by DezTheDapperImp** [comment] 2022-03-27 17:27
Found another, I'm currently in the sleeve bitnode so I can't make a gang if I remember right; and it's saying I can't use the faction/work.js because I'm not in one.

RUNTIME ERROR
/factions/work.js@home

Must have joined gang
stack:
Error: Must have joined gang
at u (file:///D:/Gaming/Video%20Games/Platforms/Steam/steamapps/common/Bitburner/resources/app/main.bundle.js:19:263447)
at Object.getGangInformation (file:///D:/Gaming/Video%20Games/Platforms/Steam/steamapps/common/Bitburner/resources/app/main.bundle.js:19:264514)
at blob:file:///d4e5aaa3-f4cb-48ee-9036-ddf231793bef:11:41
at Array.filter ()
at Module.main (blob:file:///d4e5aaa3-f4cb-48ee-9036-ddf231793bef:10:44)
at executeJSScript (file:///D:/Gaming/Video%20Games/Platforms/Steam/steamapps/common/Bitburner/resources/app/main.bundle.js:19:90945)

**Comment by mirkoconsiglio** [comment] 2022-03-29 08:15
Squashed that bug as well, everything should be working as intended now, let me know if you encounter any more bugs.

**Closed as completed by mirkoconsiglio** 2022-03-29 08:15 UTC
Labels: bug
